/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;

public class App {
    public static void main(String[] args) {
        try (Server server = new Server()) {
            server.start();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
